---
title: "R Notebook"
output: html_notebook
---


```{r loading packages}
.libPaths("/home/linfeng/R/x86_64-pc-linux-gnu-library/3.4") 

library(pacman)
library(datasets)
library(tidyverse)
library(VennDiagram)
library(devtools)
#library(MethylToSNP)
library(GGally)
library(ggfortify)
library(cowplot)
library(psych)
library(reshape)
library(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
library(meffil)
library(missMethyl)

pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, 
               ggvis, httr, lubridate, plotly, rio, rmarkdown, 
               shiny, stringr, tidyr)


```


```{r}
df <- data.frame(Germlayer_pairs = c("Ecto_Endo", "Ecto_Meso","Endo_Meso"), Count = c(12, 8, 10))

ggplot(data=df, aes(x=Germlayer_pairs, y=Count, fill=Germlayer_pairs)) +  
  geom_bar(stat="identity", fill = "steelblue", width=0.5) + 
  geom_text(aes(label=Count), hjust=1.6, color="white", size=9) +  
  coord_flip() + 
  theme(axis.title = element_text(size=12, face="bold"),
        axis.text.x = element_text(face="bold", 
                           size=10),
          axis.text.y = element_text(face="bold",  color="#993333",size=10)) + 
  scale_y_continuous(breaks=seq(0,13,2)) +
  xlab("Germ layer pair") + ylab("Number of individuals")

```


```{r}
grid.newpage()
draw.pairwise.venn(area1 = 2050,
                   area2 = 2423,
                   cross.area = 47)
```


